package com.example.flora.data.database.dao

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import com.example.flora.data.database.entities.PlantHealthLog
import kotlinx.coroutines.flow.Flow

@Dao
interface PlantHealthLogDao {
    @Query(
        """
        SELECT l.* FROM plant_health_logs l
        INNER JOIN plants p ON p.id = l.plantId
        WHERE l.plantId = :plantId AND p.userId = :userId
        ORDER BY l.timestamp DESC
        """
    )
    fun getLogsByPlantForUser(plantId: Int, userId: Int): Flow<List<PlantHealthLog>>

    @Query("SELECT * FROM plant_health_logs ORDER BY timestamp DESC")
    fun getAllLogs(): Flow<List<PlantHealthLog>>

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insert(log: PlantHealthLog)

    /** Insert + return the autogenerated row id. Used by undo flow to delete later. */
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertReturningId(log: PlantHealthLog): Long

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertAll(logs: List<PlantHealthLog>)

    @Query("DELETE FROM plant_health_logs WHERE id = :logId")
    suspend fun deleteById(logId: Int)

    @Query("DELETE FROM plant_health_logs WHERE plantId = :plantId")
    suspend fun deleteByPlant(plantId: Int)

    /**
     * Most recent unresolved Disease log for a plant — drives the disease chip
     * shown on the My Plants list card.
     */
    @Query(
        """
        SELECT * FROM plant_health_logs
        WHERE plantId = :plantId AND logType = 'Disease' AND isResolved = 0
        ORDER BY timestamp DESC
        LIMIT 1
        """
    )
    fun getActiveDiseaseLog(plantId: Int): Flow<PlantHealthLog?>

    /** Active diseases across all plants for the current user. */
    @Query(
        """
        SELECT l.* FROM plant_health_logs l
        INNER JOIN plants p ON p.id = l.plantId
        WHERE p.userId = :userId AND l.logType = 'Disease' AND l.isResolved = 0
        ORDER BY l.timestamp DESC
        """
    )
    fun getActiveDiseaseLogsForUser(userId: Int): Flow<List<PlantHealthLog>>

    @Query(
        """
        DELETE FROM plant_health_logs
        WHERE plantId IN (SELECT id FROM plants WHERE userId = :userId)
        """
    )
    suspend fun deleteAllForUser(userId: Int)
}
